#!/bin/bash
# Example shell script to launch proteus shell from a standard
#  layout. See redeploy for how this layout is typically setup.

CONFIG_CLASS=com.example.app.config.MyAppConfig
PROPERTIES="file:///srv/tomcat/proteus-worker/conf/stage.properties"

java -Dspring.config=${CONFIG_CLASS} \
  -Dspring.properties=${PROPERTIES} \
  -javaagent:$HOME/src/runtime-aspects/spring-instrument.jar \
  -javaagent:$HOME/src/runtime-aspects/aspectjweaver.jar \
  -cp "$HOME/deployed-war/WEB-INF/lib/*:$HOME/provided-libs/*" \
  net.proteusframework.shell.ProteusShell "$@"

